name: lewm
train_script: scripts/train/lewm.py
default:
  all:
    region: us
    cloud: community
    data: ogb
    dataset_name: galilai-group/ogb_cube_single
    hf_repo: flamma77/lewm-base
    hf_prefix: lewm
  train:
    gpu: NVIDIA GeForce RTX 5090
    wandb_project: lewm-tdv
    wandb.enabled: true
    hf.enabled: true
    trainer.max_epochs: 10
    num_workers: 6
    batch_size: 128
  mpc:
    seed: 7
    num_eval: 2000
    batch_size: 50
    eval_output_dir: data
    eval_output_hf: true
    stack: 1
    solver: icem
    platform:
      - gpu: NVIDIA RTX A5000
        batch_size: 150
        cloud: community
        region: any
      - gpu: NVIDIA RTX A4000
        batch_size: 100
        cloud: community
      - gpu: NVIDIA RTX 4000 Ada Generation
        batch_size: 150
        cloud: secure
      - gpu: NVIDIA RTX 5000 Ada Generation
        batch_size: 250
        cloud: community
      - gpu: NVIDIA L40
        batch_size: 350
        cloud: community
        region: any
  plan:
    seed: 42
    num_eval: 200
    batch_size: 50
    num_candidates: 64
    eval_output_dir: data
    eval_output_hf: true
    stack: 1
    platform:
      - gpu: NVIDIA GeForce RTX 4080 Super
        batch_size: 100
        cloud: community
        region: any
      - gpu: NVIDIA RTX 2000 Ada Generation
        batch_size: 100
        cloud: secure
        region: any
      - gpu: NVIDIA RTX 2000 Ada Generation
        batch_size: 100
        cloud: secure
        region: any
      - gpu: NVIDIA RTX A4000
        batch_size: 100
        cloud: community
param_map:
  data: data
  dataset_name: data.dataset.name
  hf_repo: hf.repo_id
  wandb_project: wandb.config.project
  hf_prefix: hf.path_prefix
  batch_size: loader.batch_size
  lam: loss.sigreg.weight
  lr: optimizer.lr
job0:
  mode: train
  params:
    lam: 0.1
    lr: 5.0e-05
  pod_id: 6tj6cj4xwawmxj
  status: running
  output_model_name: lewm_lam0.1_lr5e-5
job1:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 7
  num_eval: 2000
  solver: icem
  status: running
  pod_ids:
    - j3qv5g8tgr9g6r
  pod_id: j3qv5g8tgr9g6r
job2:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 42
  num_eval: 5000
  solver: cem
  status: running
  pod_ids:
    - gfbjawn89ubdtw
  pod_id: gfbjawn89ubdtw
job3:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 7
  num_eval: 5000
  solver: cem
  status: running
  pod_ids:
    - tvubi5109mvj8m
  pod_id: tvubi5109mvj8m
job4:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 101
  num_eval: 2000
  solver: icem
  status: running
  pod_ids:
    - vfizedblmojha5
  pod_id: vfizedblmojha5
job5:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 42
  num_eval: 2000
  solver: icem
  status: running
  pod_ids:
    - hvejl3r4ufbwn5
  pod_id: hvejl3r4ufbwn5
job6:
  mode: plan
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 7
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - 1itl3kkh6d9atg
  pod_id: 1itl3kkh6d9atg
job7:
  mode: plan
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 101
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - zmsdfec244hhb4
  pod_id: zmsdfec244hhb4
job8:
  mode: plan
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 42
  num_eval: 200
  num_candidates: 64
  status: completed
job9:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 101
  num_eval: 5000
  solver: cem
  status: running
  pod_ids:
    - zb8fw2j36t88pg
  pod_id: zb8fw2j36t88pg
job10:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 42
  num_eval: 2000
  solver: icem
  status: running
  pod_ids:
    - 6t386t4dlnflof
  pod_id: 6t386t4dlnflof
job11:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 101
  num_eval: 2000
  solver: icem
  status: running
  pod_ids:
    - 12fm9q3ddg5ee2
  pod_id: 12fm9q3ddg5ee2
job12:
  mode: plan
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 42
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - uqb2s2m8hirr49
  pod_id: uqb2s2m8hirr49
job13:
  mode: plan
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 101
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - 8wv1szmcuyily7
  pod_id: 8wv1szmcuyily7
job14:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 42
  num_eval: 2000
  solver: adam
  status: completed
job15:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 7
  num_eval: 2000
  solver: adam
  status: completed
job16:
  mode: mpc
  output_model_name: lewm_lam0.1_lr5e-5
  seed: 101
  num_eval: 2000
  solver: adam
  status: completed
job17:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 101
  num_eval: 2000
  solver: adam
  status: completed
