name: tdv
train_script: scripts/train/lewm_tdv.py
default:
  all:
    region: ca
    cloud: community
    data: ogb
    dataset_name: galilai-group/ogb_cube_single
    hf_repo: flamma77/lewm-base
    hf_prefix: tdv
  train:
    gpu: NVIDIA GeForce RTX 5090
    wandb_project: lewm-tdv
    wandb.enabled: true
    hf.enabled: true
    trainer.max_epochs: 10
    num_workers: 6
    batch_size: 128
  mpc:
    region: any
    cloud: community
    seed: 7
    num_eval: 2000
    batch_size: 150
    eval_output_dir: data
    eval_output_hf: true
    stack: 1
    solver: icem
    platform:
      - gpu: NVIDIA RTX 4000 Ada Generation
        batch_size: 150
        cloud: secure
      - gpu: NVIDIA A40
        batch_size: 150
        cloud: secure
      - gpu: NVIDIA L4
        batch_size: 150
        cloud: secure
      - gpu: NVIDIA RTX 2000 Ada Generation
        batch_size: 100
        cloud: secure
      - gpu: NVIDIA RTX A4000
        batch_size: 100
        cloud: secure
  plan:
    seed: 42
    num_eval: 200
    batch_size: 50
    num_candidates: 64
    eval_output_dir: data
    eval_output_hf: true
    stack: 1
    platform:
      - gpu: NVIDIA RTX 2000 Ada Generation
        batch_size: 100
        cloud: secure
        region: any
      - gpu: NVIDIA RTX A4000
        batch_size: 100
        cloud: community
      - gpu: NVIDIA GeForce RTX 4090
        batch_size: 100
        cloud: community
        region: canada
param_map:
  data: data
  dataset_name: data.dataset.name
  hf_repo: hf.repo_id
  wandb_project: wandb.config.project
  hf_prefix: hf.path_prefix
  batch_size: loader.batch_size
  a: loss.tdv.weight
  lam: loss.sigreg.weight
  lr: optimizer.lr
job0:
  mode: mpc
  output_model_name: start22_a0.0_l0.1_lr5e-5
  pod_id: dkiilihfi7bir1
  status: completed
job1:
  mode: mpc
  output_model_name: start22_a1.0_l0.15_lr5e-5
  pod_id: fsgpe4f16xnd0c
  status: completed
job2:
  mode: mpc
  output_model_name: start22_a1.0_l0.2_lr5e-5
  pod_id: nkmgr7o2uok4ef
  status: completed
job3:
  mode: mpc
  output_model_name: start22_a2.0_l0.1_lr5e-5
  status: completed
job4:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  status: completed
job5:
  mode: train
  params:
    a: 0.0
    lam: 0.1
    lr: '2.5e-5'
  pod_id: ck1hrmn362y58q
  status: running
  output_model_name: tdv_a0.0_lam0.1_lr2.5e-5
job6:
  mode: train
  params:
    a: 0.0
    lam: 0.1
    lr: 0.0001
  pod_id: 9osyj19hrz6g63
  status: running
  output_model_name: tdv_a0.0_lam0.1_lr1e-4
job7:
  mode: train
  params:
    a: 1.0
    lam: 0.2
    lr: '2.5e-5'
  pod_id: 5q33euqi79hyju
  status: running
  output_model_name: tdv_a1.0_lam0.2_lr2.5e-5
job8:
  mode: train
  params:
    a: 1.0
    lam: 0.2
    lr: 0.0001
  pod_id: 7errqu1q66za86
  status: running
  output_model_name: tdv_a1.0_lam0.2_lr1e-4
job9:
  mode: train
  params:
    a: 1.0
    lam: 0.25
    lr: 5.0e-05
  pod_id: tkd0gs1c8gtk91
  status: running
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
job10:
  mode: plan
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  status: completed
job11:
  mode: plan
  output_model_name: start22_a0.0_l0.1_lr5e-5
  status: completed
job12:
  mode: plan
  output_model_name: start22_a1.0_l0.2_lr5e-5
  status: completed
job13:
  mode: mpc
  output_model_name: tdv_a0.0_lam0.1_lr2.5e-5
  pod_id: u7jltzdwjtbzq3
  status: completed
job14:
  mode: mpc
  output_model_name: tdv_a0.0_lam0.1_lr1e-4
  pod_id: u7jltzdwjtbzq3
  status: completed
job15:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.2_lr2.5e-5
  pod_id: u7jltzdwjtbzq3
  status: completed
job16:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.2_lr1e-4
  status: completed
job17:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  pod_id: 73ajihdei48xeb
  status: completed
job18:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr2.5e-5
  status: completed
job19:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr1e-4
  status: completed
job20:
  mode: plan
  output_model_name: tdv_a0.0_lam0.1_lr2.5e-5
  status: completed
job21:
  mode: plan
  output_model_name: tdv_a1.0_lam0.25_lr2.5e-5
  status: completed
job22:
  mode: plan
  output_model_name: tdv_a1.0_lam0.25_lr1e-4
  status: completed
job23:
  mode: plan
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  status: completed
job24:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 101
  num_eval: 5000
  solver: cem
  status: completed
job25:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 101
  num_eval: 5000
  solver: cem
  status: completed
job26:
  mode: mpc
  output_model_name: start22_a0.0_l0.1_lr5e-5
  seed: 101
  num_eval: 5000
  solver: cem
  status: completed
job27:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 7
  num_eval: 5000
  solver: cem
  status: completed
job28:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 7
  num_eval: 5000
  solver: cem
  status: completed
job29:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 42
  num_eval: 5000
  solver: cem
  status: completed
job30:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 42
  num_eval: 5000
  solver: cem
  status: completed
job31:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 42
  num_eval: 2000
  solver: icem
  status: running
  pod_ids:
    - 97b141gnuv3fl2
  pod_id: 97b141gnuv3fl2
job32:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 42
  num_eval: 2000
  solver: icem
  status: completed
job33:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 101
  num_eval: 2000
  solver: icem
  status: running
  pod_ids:
    - 1s3vve8swxiwom
  pod_id: 1s3vve8swxiwom
job34:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 101
  num_eval: 2000
  solver: icem
  status: completed
job35:
  mode: plan
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 7
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - etbds7t9oyvuqy
  pod_id: etbds7t9oyvuqy
job36:
  mode: plan
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 7
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - aipkbzls4wgdwl
  pod_id: aipkbzls4wgdwl
job37:
  mode: plan
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 42
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - jmcnzzwkw5dryi
  pod_id: jmcnzzwkw5dryi
job38:
  mode: plan
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 101
  num_eval: 200
  num_candidates: 64
  status: running
  pod_ids:
    - whlxo0uz2jejyw
  pod_id: whlxo0uz2jejyw
job39:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 42
  num_eval: 2000
  solver: adam
  status: running
  pod_ids:
    - crd3omzlkiu2kd
  pod_id: crd3omzlkiu2kd
job40:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 42
  num_eval: 2000
  solver: adam
  status: running
  pod_ids:
    - ej2n4ygbnc87wb
  pod_id: ej2n4ygbnc87wb
job41:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 7
  num_eval: 2000
  solver: adam
  status: running
  pod_ids:
    - 93z21oznerhuc8
  pod_id: 93z21oznerhuc8
job42:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 7
  num_eval: 2000
  solver: adam
  status: running
  pod_ids:
    - jlb6mq0u1bsroh
  pod_id: jlb6mq0u1bsroh
job43:
  mode: mpc
  output_model_name: quentinll/lewm-cube
  is_hf_model: true
  seed: 101
  num_eval: 2000
  solver: adam
  status: running
  pod_ids:
    - 1w1pe1c9osdumq
  pod_id: 1w1pe1c9osdumq
job44:
  mode: mpc
  output_model_name: tdv_a1.0_lam0.25_lr5e-5
  seed: 101
  num_eval: 2000
  solver: adam
  status: running
  pod_ids:
    - 5wvwfg5mem9xf2
  pod_id: 5wvwfg5mem9xf2
