name: visreg
train_script: scripts/train/lewm_visreg.py
default:
  all:
    region: ca
    cloud: community
    data: ogb
    dataset_name: galilai-group/ogb_cube_single
    hf_repo: flamma77/lewm-base
    hf_prefix: visreg
  train:
    gpu: NVIDIA GeForce RTX 5090
    wandb_project: lewm-visreg
    wandb.enabled: true
    hf.enabled: true
    trainer.max_epochs: 10
    num_workers: 6
    batch_size: 128
  mpc:
    seed: 7
    num_eval: 2000
    batch_size: 50
    eval_output_dir: data
    eval_output_hf: true
    platform:
      - gpu: NVIDIA GeForce RTX 4070 Ti
        batch_size: 100
        cloud: community
      - gpu: NVIDIA RTX A4500
        batch_size: 200
        cloud: community
      - gpu: NVIDIA RTX A4000
        batch_size: 150
        cloud: community
      - gpu: Tesla V100-SXM2-16GB
        batch_size: 150
        cloud: community
      - gpu: NVIDIA GeForce RTX 3070
        batch_size: 50
        cloud: community
  plan:
    seed: 42
    num_eval: 200
    batch_size: 50
    num_candidates: 64
    eval_output_dir: data
    eval_output_hf: true
    platform:
      - gpu: NVIDIA GeForce RTX 4070 Ti
        batch_size: 100
        cloud: community
      - gpu: NVIDIA RTX A4500
        batch_size: 200
        cloud: community
      - gpu: NVIDIA RTX A4000
        batch_size: 150
        cloud: community
      - gpu: Tesla V100-SXM2-16GB
        batch_size: 150
        cloud: community
      - gpu: NVIDIA GeForce RTX 3070
        batch_size: 50
        cloud: community
param_map:
  data: data
  dataset_name: data.dataset.name
  hf_repo: hf.repo_id
  wandb_project: wandb.config.project
  hf_prefix: hf.path_prefix
  batch_size: loader.batch_size
  a: loss.visreg.alpha
  lr: optimizer.lr
  lsh: loss.visreg.lam_shape
  lce: loss.visreg.lam_center
  lsc: loss.visreg.lam_scale
job0:
  mode: train
  params:
    a: 0.01
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: 17dxbl1v9psekl
  status: running
  output_model_name: visreg_a0.01_lsc1.0_lce1.0_lsh1.0_lr5e-5
job1:
  mode: train
  params:
    a: 0.03
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: 3itga4oiwxufgk
  status: running
  output_model_name: visreg_a0.03_lsc1.0_lce1.0_lsh1.0_lr5e-5
job2:
  mode: train
  params:
    a: 0.1
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: b19rfng3jaelwa
  status: running
  output_model_name: visreg_a0.1_lsc1.0_lce1.0_lsh1.0_lr5e-5
job3:
  mode: train
  params:
    a: 0.3
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: wi4h591fpqi3l1
  status: running
  output_model_name: visreg_a0.3_lsc1.0_lce1.0_lsh1.0_lr5e-5
job4:
  mode: train
  params:
    a: 1.0
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: vl07q5ljz4y393
  status: running
  output_model_name: visreg_a1.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
job5:
  mode: train
  params:
    a: 3.0
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: pza3z4bzeq7csw
  status: running
  output_model_name: visreg_a3.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
job6:
  mode: train
  params:
    a: 0.3
    lsc: 0.5
    lce: 2.0
    lsh: 0.5
    lr: 5.0e-05
  pod_id: 5vq8t8qq6w0od0
  status: running
  output_model_name: visreg_a0.3_lsc0.5_lce2.0_lsh0.5_lr5e-5
job7:
  mode: train
  params:
    a: 0.3
    lsc: 2.0
    lce: 0.5
    lsh: 0.5
    lr: 5.0e-05
  pod_id: v1qx6asd0gty2u
  status: running
  output_model_name: visreg_a0.3_lsc2.0_lce0.5_lsh0.5_lr5e-5
job8:
  mode: train
  params:
    a: 0.3
    lsc: 0.5
    lce: 0.5
    lsh: 2.0
    lr: 5.0e-05
  pod_id: nsr9f5a7fixjaz
  status: running
  output_model_name: visreg_a0.3_lsc0.5_lce0.5_lsh2.0_lr5e-5
job9:
  mode: train
  params:
    a: 0.3
    lsc: 2.0
    lce: 0.5
    lsh: 0.5
    lr: 5.0e-05
  pod_id: s9qsubj1i60nxb
  status: running
  output_model_name: visreg_a0.3_lsc2.0_lce0.5_lsh0.5_lr5e-5
job10:
  mode: train
  params:
    a: 4.0
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: 2svn44srfqs9u9
  status: running
  output_model_name: visreg_a4.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
job11:
  mode: train
  params:
    a: 1.0
    lsc: 0.75
    lce: 0.75
    lsh: 1.25
    lr: 5.0e-05
  pod_id: o4fakhljycklng
  status: running
  output_model_name: visreg_a1.0_lsc0.75_lce0.75_lsh1.25_lr5e-5
job12:
  mode: train
  params:
    a: 1.0
    lsc: 0.5
    lce: 0.5
    lsh: 2.0
    lr: 5.0e-05
  pod_id: t7koon5s3fmdbw
  status: running
  output_model_name: visreg_a1.0_lsc0.5_lce0.5_lsh2.0_lr5e-5
job13:
  mode: mpc
  output_model_name: visreg_a0.3_lsc1.0_lce1.0_lsh1.0_lr5e-5
  pod_id: 2d3zyw50faupna
  status: running
job14:
  mode: mpc
  output_model_name: visreg_a1.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
  pod_id: bu19h8sfosc3su
  status: running
job15:
  mode: mpc
  output_model_name: visreg_a3.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
  pod_id: 2x9yfhbnb5eqs2
  status: running
job16:
  mode: mpc
  output_model_name: visreg_a0.3_lsc2.0_lce0.5_lsh0.5_lr5e-5
  pod_id: bgff5foh3x5835
  status: running
job17:
  mode: mpc
  output_model_name: visreg_a4.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
  pod_id: oh4u0dr064ii7o
  status: running
job18:
  mode: mpc
  output_model_name: visreg_a1.0_lsc0.75_lce0.75_lsh1.25_lr5e-5
  pod_id: ibivjyz7w0k1na
  status: running
job19:
  mode: train
  params:
    a: 6.0
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: dgwzdoh8wvo4t4
  status: running
  output_model_name: visreg_a6.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
job20:
  mode: train
  params:
    a: 8.0
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: b7fgqwu2cm27pe
  status: running
  output_model_name: visreg_a8.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
job21:
  mode: train
  params:
    a: 12.0
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
  pod_id: 2oyyijqtgembzj
  status: running
  output_model_name: visreg_a12.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
job22:
  mode: train
  params:
    a: 16.0
    lsc: 1.0
    lce: 1.0
    lsh: 1.0
    lr: 5.0e-05
job23:
  mode: plan
  output_model_name: visreg_a4.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
  status: completed
job24:
  mode: mpc
  output_model_name: visreg_a6.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
  status: completed
job25:
  mode: mpc
  output_model_name: visreg_a8.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
  status: completed
job26:
  mode: plan
  output_model_name: visreg_a6.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
job27:
  mode: plan
  output_model_name: visreg_a8.0_lsc1.0_lce1.0_lsh1.0_lr5e-5
